# -*- coding: utf-8 -*-
"""Lagrange Points

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ID6kgk2_7tTRfDenSzo_aCmiX4fHLhWj
"""

import numpy as np
import matplotlib.pyplot as plt

from scipy.integrate import solve_ivp
from scipy.optimize import root_scalar
from matplotlib.animation import FuncAnimation, PillowWriter

G = 6.67430e-11

# Massed (Kg)
m1 = 1.98847e30  #Sun
m2 = 5.9722e24   #Earth
m3 = 1000.0      #Satellite

# Sun-Earth distance (m)
D = 1.495978707e11

# Dimensionless mass parameter
mu = m2 / (m1 + m2)

# Angular velocity of Sun-Earth system
omega = np.sqrt(G * (m1 + m2) / D**3)

print("mu =", mu)
print("omega =", omega, "rad/s")

# Calculate L1, L2, L3
def collinear_equation(x):
  r1 = abs(x + mu)
  r2 = abs(x - (1.0 - mu))

  return (x - (1.0 - mu) * (x + mu) / r1**3
            - mu * (x - (1.0 - mu)) / r2**3 )

# L1
solution_L1 = root_scalar(
    collinear_equation,
    bracket=(0.9, 1.0 - mu - 1e-8),
    xtol=1e-14)

x_L1_rot = solution_L1.root
y_L1_rot = 0.0

# L2
solution_L2 = root_scalar(
    collinear_equation,
    bracket=(1.0 - mu + 1e-8, 1.1),
    xtol=1e-14)

x_L2_rot = solution_L2.root
y_L2_rot = 0.0

# L3
solution_L3 = root_scalar(
    collinear_equation,
    bracket=(-1.1, -mu - 1e-8),
    xtol=1e-14)

x_L3_rot = solution_L3.root
y_L3_rot = 0.0

# Calculate L4, L5
x_L4_rot = 0.5 - mu
y_L4_rot = np.sqrt(3.0) / 2.0

x_L5_rot = 0.5 - mu
y_L5_rot = -np.sqrt(3.0) / 2.0

print("\nLagrange points in rotating normalized coordinates:")

print("L1 =", x_L1_rot, y_L1_rot)
print("L2 =", x_L2_rot, y_L2_rot)
print("L3 =", x_L3_rot, y_L3_rot)
print("L4 =", x_L4_rot, y_L4_rot)
print("L5 =", x_L5_rot, y_L5_rot)

# Initial Positions
x1 = -mu * D
y1 = 0.0

x2 = (1.0 - mu) * D
y2 = 0.0

# Satellite starts at L1
perturbation = 1.0e7

#x3 = x_L1_rot * D + perturbation
x3 = x_L1_rot * D
y3 = 0.0

# Initial Velocities
vx1 = 0.0
vy1 = omega * x1

vx2 = 0.0
vy2 = omega * x2

vx3 = 0.0
vy3 = omega * x3

print("\nInitial velocities:")

print("Earth velocity =", vy2 / 1000.0, "km/s")

print("Satellite velocity =", vy3 / 1000.0, "km/s")

initial_state = [
    x1, y1, vx1, vy1,
    x2, y2, vx2, vy2,
    x3, y3, vx3, vy3
]

def three_body_ode(t, state):
    x1, y1, vx1, vy1, \
    x2, y2, vx2, vy2, \
    x3, y3, vx3, vy3 = state

    # Distances between bodies
    r12 = np.sqrt((x2 - x1)**2 + (y2 - y1)**2)
    r13 = np.sqrt((x3 - x1)**2 + (y3 - y1)**2)
    r23 = np.sqrt((x3 - x2)**2 + (y3 - y2)**2)

    # Acceleration of Body 1
    ax1 = G * m2 * (x2 - x1) / r12**3 \
        + G * m3 * (x3 - x1) / r13**3

    ay1 = G * m2 * (y2 - y1) / r12**3 \
        + G * m3 * (y3 - y1) / r13**3

    # Acceleration of Body 2
    ax2 = G * m1 * (x1 - x2) / r12**3 \
        + G * m3 * (x3 - x2) / r23**3

    ay2 = G * m1 * (y1 - y2) / r12**3 \
        + G * m3 * (y3 - y2) / r23**3

    # Acceleration of Body 3
    ax3 = G * m1 * (x1 - x3) / r13**3 \
        + G * m2 * (x2 - x3) / r23**3

    ay3 = G * m1 * (y1 - y3) / r13**3 \
        + G * m2 * (y2 - y3) / r23**3

     # 12 first-order ODEs
    return [
        vx1, vy1, ax1, ay1,
        vx2, vy2, ax2, ay2,
        vx3, vy3, ax3, ay3
    ]

# Time interval
day = 24.0 * 60.0 * 60.0

t_start = 0.0
t_end = 365.25 * day

t_eval = np.linspace(t_start, t_end, 1500)

# Solve ODE
solution = solve_ivp(
    three_body_ode,
    (t_start, t_end),
    initial_state,
    t_eval=t_eval,
    rtol=1e-9,
    atol=1e-9
)

# Extract Sun, Earth, Satellite positions
x1 = solution.y[0]
y1 = solution.y[1]

x2 = solution.y[4]
y2 = solution.y[5]

x3 = solution.y[8]
y3 = solution.y[9]

# Convert to AU
x1_AU = x1 / D
y1_AU = y1 / D

x2_AU = x2 / D
y2_AU = y2 / D

x3_AU = x3 / D
y3_AU = y3 / D

# Rotate Lagrange points into inertial frame
theta = omega * solution.t

def rotating_to_inertial(x_rot, y_rot, theta):

    x = (x_rot * np.cos(theta) - y_rot * np.sin(theta))

    y = (x_rot * np.sin(theta) + y_rot * np.cos(theta))

    return x, y

# L1
x_L1_AU, y_L1_AU = rotating_to_inertial(x_L1_rot, y_L1_rot, theta)

# L2
x_L2_AU, y_L2_AU = rotating_to_inertial(x_L2_rot, y_L2_rot, theta)

# L3
x_L3_AU, y_L3_AU = rotating_to_inertial(x_L3_rot, y_L3_rot, theta)

# L4
x_L4_AU, y_L4_AU = rotating_to_inertial(x_L4_rot, y_L4_rot, theta)

# L5
x_L5_AU, y_L5_AU = rotating_to_inertial(x_L5_rot, y_L5_rot, theta)


# Visual separation for L1 and L2
#
# L1 and L2 are very close to Earth, so they are difficult
# to see on a full Sun-Earth plot.
#
# This changes ONLY the display position.

display_scale = 6.0

x_L1_display = (x2_AU + display_scale * (x_L1_AU - x2_AU))

y_L1_display = (y2_AU + display_scale * (y_L1_AU - y2_AU))

x_L2_display = (x2_AU + display_scale * (x_L2_AU - x2_AU))

y_L2_display = (y2_AU + display_scale * (y_L2_AU - y2_AU))

# Optional satellite display scaling
x3_display = (x2_AU + display_scale * (x3_AU - x2_AU))

y3_display = (y2_AU + display_scale * (y3_AU - y2_AU))


# Create Figure
fig, ax = plt.subplots(
    figsize=(8, 8)
)

ax.set_xlim(-1.2, 1.2)
ax.set_ylim(-1.2, 1.2)

ax.set_aspect("equal")

ax.set_xlabel("x (AU)")
ax.set_ylabel("y (AU)")

ax.set_title(
    "Sun-Earth System with Lagrange Points"
)

ax.grid()

# Create objects
sun, = ax.plot(
    [],
    [],
    "o",
    markersize=12,
    label="Sun"
)

earth, = ax.plot(
    [],
    [],
    "o",
    markersize=8,
    label="Earth"
)


# Actual satellite from ODE
satellite, = ax.plot(
    [],
    [],
    "o",
    markersize=4,
    label="Satellite (L1)"
)

# Lagrange points
'''L1_point, = ax.plot(
    [],
    [],
    "o",
    markersize=5,
    label="L1"
)'''

L2_point, = ax.plot(
    [],
    [],
    "o",
    markersize=5,
    label="L2"
)

L3_point, = ax.plot(
    [],
    [],
    "o",
    markersize=5,
    label="L3"
)

L4_point, = ax.plot(
    [],
    [],
    "o",
    markersize=5,
    label="L4"
)

L5_point, = ax.plot(
    [],
    [],
    "o",
    markersize=5,
    label="L5"
)


# Sun-Earth connecting line
'''sun_earth_line, = ax.plot(
    [],
    [],
    "--",
    alpha=0.5
)'''

# L2-L3 line
L2_L3_line, = ax.plot(
    [],
    [],
    "--",
    color="gray",
    alpha=0.5
)

# Upper triangle
sun_L4_line, = ax.plot(
    [],
    [],
    "--",
    color=L4_point.get_color(),
    alpha=0.5
)

L4_earth_line, = ax.plot(
    [],
    [],
    "--",
    color=L4_point.get_color(),
    alpha=0.5
)

# Lower triangle
sun_L5_line, = ax.plot(
    [],
    [],
    "--",
    color=L5_point.get_color(),
    alpha=0.5
)

L5_earth_line, = ax.plot(
    [],
    [],
    "--",
    color=L5_point.get_color(),
    alpha=0.5
)

# Real Trajectory Trails
earth_trail, = ax.plot(
    [],
    [],
    "-",
    color=earth.get_color(),
    alpha=0.25
)

satellite_trail, = ax.plot(
    [],
    [],
    "-",
    color=satellite.get_color(),
    alpha=0.25
)


ax.legend(
    loc="upper right"
)

# Animation update function
def update(frame):

    # Sun
    sun.set_data(
        [x1_AU[frame]], [y1_AU[frame]])

    # Earth
    earth.set_data(
        [x2_AU[frame]], [y2_AU[frame]])

    # Satellite marker
    satellite.set_data(
        [x3_display[frame]], [y3_display[frame]])

    # For perturbation
    #satellite.set_data(
    #    [x3_AU[frame]], [y3_AU[frame]])

    # L1
    #L1_point.set_data(
    #    [x_L1_display[frame]], [y_L1_display[frame]])

    # L2
    L2_point.set_data(
        [x_L2_display[frame]], [y_L2_display[frame]])

    # L3
    L3_point.set_data(
        [x_L3_AU[frame]], [y_L3_AU[frame]])

    # L4
    L4_point.set_data(
        [x_L4_AU[frame]], [y_L4_AU[frame]])

    # L5
    L5_point.set_data(
        [x_L5_AU[frame]], [y_L5_AU[frame]])

    # Sun-Earth line
    #sun_earth_line.set_data(
    #    [x1_AU[frame], x2_AU[frame]], [y1_AU[frame], y2_AU[frame]])

    # L2-L3 line
    L2_L3_line.set_data(
        [x_L2_display[frame], x_L3_AU[frame]],
        [y_L2_display[frame], y_L3_AU[frame]])

    # Sun -> L4
    sun_L4_line.set_data(
        [x1_AU[frame], x_L4_AU[frame]],
        [y1_AU[frame], y_L4_AU[frame]])

    # L4 -> Earth
    L4_earth_line.set_data(
        [x_L4_AU[frame], x2_AU[frame]],
        [y_L4_AU[frame], y2_AU[frame]])

    # Sun -> L5
    sun_L5_line.set_data(
        [x1_AU[frame], x_L5_AU[frame]],
        [y1_AU[frame], y_L5_AU[frame]])

    # L5 -> Earth
    L5_earth_line.set_data(
        [x_L5_AU[frame], x2_AU[frame]],
        [y_L5_AU[frame], y2_AU[frame]])

    # Earth trail
    earth_trail.set_data(
        x2_AU[:frame + 1], y2_AU[:frame + 1])

    # Satellite DISPLAY trail
    satellite_trail.set_data(
        x3_display[:frame + 1], y3_display[:frame + 1])

    # For perturbation
    #satellite_trail.set_data(
    #    x3_AU[:frame + 1], y3_AU[:frame + 1])

    return (
        sun,
        earth,
        satellite,
        #L1_point,
        L2_point,
        L3_point,
        L4_point,
        L5_point,
        #sun_earth_line,
        L2_L3_line,
        sun_L4_line,
        L4_earth_line,
        sun_L5_line,
        L5_earth_line,
        earth_trail,
        satellite_trail
    )

# Create animation
import matplotlib.pyplot as plt
# Increase the embedding limit to 50 MB to allow the complete animation
plt.rcParams["animation.embed_limit"] = 50

animation = FuncAnimation(
    fig,
    update,
    # range(start, stop, step): use every 5th solution point
    frames=range(0, len(solution.t), 5),

    # 30 ms delay between consecutive frames
    interval=30,

    # Redraw only updated objects to improve rendering efficiency
    blit=True
)

# Prevent Colab from displaying an extra static figure
plt.close()


from IPython.display import HTML
# Display animation in Colab
HTML(animation.to_jshtml())

# Save GIF
animation.save(
    "three_body_Lagrange_point.gif",
    writer=PillowWriter(fps=30)
)