# -*- coding: utf-8 -*-
"""Three_body_ODE.ipynb

Automatically generated by Colab.

"""

import numpy as np
import matplotlib.pyplot as plt

from scipy.integrate import solve_ivp
from matplotlib.animation import FuncAnimation, PillowWriter

G = 1.0

m1 = 1.0
m2 = 1.0
m3 = 1.0

# Initial Positions
x1, y1 = -0.97000436,  0.24308753
x2, y2 =  0.97000436, -0.24308753
x3, y3 =  0.0,          0.0

# Initial Velocities
vx1, vy1 =  0.466203685,  0.432365730
vx2, vy2 =  0.466203685,  0.432365730
vx3, vy3 = -0.93240737,  -0.86473146

from google.colab import drive
drive.mount('/content/drive')

initial_state = [
    x1, y1, vx1, vy1,
    x2, y2, vx2, vy2,
    x3, y3, vx3, vy3
]

def three_body_ode(t, state):
    x1, y1, vx1, vy1, \
    x2, y2, vx2, vy2, \
    x3, y3, vx3, vy3 = state

    # Distances between bodies
    r12 = np.sqrt((x2 - x1)**2 + (y2 - y1)**2)
    r13 = np.sqrt((x3 - x1)**2 + (y3 - y1)**2)
    r23 = np.sqrt((x3 - x2)**2 + (y3 - y2)**2)

    # Acceleration of Body 1
    ax1 = G * m2 * (x2 - x1) / r12**3 \
        + G * m3 * (x3 - x1) / r13**3

    ay1 = G * m2 * (y2 - y1) / r12**3 \
        + G * m3 * (y3 - y1) / r13**3

    # Acceleration of Body 2
    ax2 = G * m1 * (x1 - x2) / r12**3 \
        + G * m3 * (x3 - x2) / r23**3

    ay2 = G * m1 * (y1 - y2) / r12**3 \
        + G * m3 * (y3 - y2) / r23**3

    # Acceleration of Body 3
    ax3 = G * m1 * (x1 - x3) / r13**3 \
        + G * m2 * (x2 - x3) / r23**3

    ay3 = G * m1 * (y1 - y3) / r13**3 \
        + G * m2 * (y2 - y3) / r23**3

     # 12 first-order ODEs
    return [
        vx1, vy1, ax1, ay1,
        vx2, vy2, ax2, ay2,
        vx3, vy3, ax3, ay3
    ]

t_start = 0.0
t_end = 2 * 6.3259

t_eval = np.linspace(t_start, t_end, 2000)

solution = solve_ivp(
    three_body_ode,
    (t_start, t_end),
    initial_state,
    t_eval=t_eval,
    rtol=1e-9,
    atol=1e-9
)

# Extract positions from the solution
x1 = solution.y[0]
y1 = solution.y[1]

x2 = solution.y[4]
y2 = solution.y[5]

x3 = solution.y[8]
y3 = solution.y[9]

# Plot trajectories
plt.figure(figsize=(8, 6))

plt.plot(x1, y1, label="Body 1")
plt.plot(x2, y2, label="Body 2")
plt.plot(x3, y3, label="Body 3")

plt.xlabel("x")
plt.ylabel("y")
plt.title("Three-Body Figure-Eight Orbit")

plt.axis("equal")
plt.legend()
plt.grid()

plt.show()

fig, ax = plt.subplots(figsize=(8, 6))

ax.set_xlim(-1.2, 1.2)
ax.set_ylim(-0.5, 0.5)
ax.set_aspect("equal")

ax.set_xlabel("x")
ax.set_ylabel("y")
ax.set_title("Three-Body Figure-Eight Orbit")
ax.grid()

# Moving bodies
body1, = ax.plot([], [], "o", markersize=8, label="Body 1")
body2, = ax.plot([], [], "o", markersize=8, label="Body 2")
body3, = ax.plot([], [], "o", markersize=8, label="Body 3")

# Trails use the same colors as the bodies
trail1, = ax.plot([], [], "-", color=body1.get_color(), alpha=0.5)
trail2, = ax.plot([], [], "-", color=body2.get_color(), alpha=0.5)
trail3, = ax.plot([], [], "-", color=body3.get_color(), alpha=0.5)

ax.legend(loc="upper right")


def update(frame):
    # Trails
    trail1.set_data(x1[:frame + 1], y1[:frame + 1])
    trail2.set_data(x2[:frame + 1], y2[:frame + 1])
    trail3.set_data(x3[:frame + 1], y3[:frame + 1])

    # Current positions
    body1.set_data([x1[frame]], [y1[frame]])
    body2.set_data([x2[frame]], [y2[frame]])
    body3.set_data([x3[frame]], [y3[frame]])

    return trail1, trail2, trail3, body1, body2, body3


animation = FuncAnimation(
    fig,
    update,
    frames=range(0, len(t_eval), 5),
    interval=20,
    blit=True
)

plt.close()

from IPython.display import HTML

HTML(animation.to_jshtml())

animation.save(
    "three_body_figure_eight.gif",
    writer=PillowWriter(fps=30)
)